export const Types = {
    REMOVE_TODO:'REMOVE_TODO',
    CREATE_TODO:'CREATE_TODO',
    COMPELETED_TODO:'COMPELETED_TODO',
    LOAD_TODOS_IN_PROGRESS: 'LOAD_TODOS_IN_PROGRESS',
    LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
    LOAD_TODOS_ERROR: 'LOAD_TODOS_ERROR',
}